<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0-windows;net48</TargetFrameworks>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>default</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FlaUI.UIA3" Version="5.0.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\RichCanvas.UIAutomation.Core\RichCanvas.UIAutomation.Core.csproj" />
	</ItemGroup>

</Project>
