<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FlaUI.UIA3" Version="5.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\RichCanvas\RichCanvas.csproj" />
    <ProjectReference Include="..\RichCanvas.UIAutomation.Core\RichCanvas.UIAutomation.Core.csproj" />
  </ItemGroup>

</Project>
